version: '3.3'
services:
  application:
    image: phoenix_channel_workshop:0.0.1
    container_name: phoenix_channel_workshop
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/phoenix_channel_workshop_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:12-alpine
    container_name: phoenix_channel_workshop-postgres
    environment:
      - POSTGRES_DB=phoenix_channel_workshop_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - phoenix_channel_workshop_psql:/var/lib/postgresql/data
volumes:
  phoenix_channel_workshop_psql:
